require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CatgradesController do

  # This should return the minimal set of attributes required to create a valid
  # Catgrade. As you add validations to Catgrade, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "libcatgrade" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CatgradesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all catgrades as @catgrades" do
      catgrade = Catgrade.create! valid_attributes
      get :index, {}, valid_session
      assigns(:catgrades).should eq([catgrade])
    end
  end

  describe "GET show" do
    it "assigns the requested catgrade as @catgrade" do
      catgrade = Catgrade.create! valid_attributes
      get :show, {:id => catgrade.to_param}, valid_session
      assigns(:catgrade).should eq(catgrade)
    end
  end

  describe "GET new" do
    it "assigns a new catgrade as @catgrade" do
      get :new, {}, valid_session
      assigns(:catgrade).should be_a_new(Catgrade)
    end
  end

  describe "GET edit" do
    it "assigns the requested catgrade as @catgrade" do
      catgrade = Catgrade.create! valid_attributes
      get :edit, {:id => catgrade.to_param}, valid_session
      assigns(:catgrade).should eq(catgrade)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Catgrade" do
        expect {
          post :create, {:catgrade => valid_attributes}, valid_session
        }.to change(Catgrade, :count).by(1)
      end

      it "assigns a newly created catgrade as @catgrade" do
        post :create, {:catgrade => valid_attributes}, valid_session
        assigns(:catgrade).should be_a(Catgrade)
        assigns(:catgrade).should be_persisted
      end

      it "redirects to the created catgrade" do
        post :create, {:catgrade => valid_attributes}, valid_session
        response.should redirect_to(Catgrade.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved catgrade as @catgrade" do
        # Trigger the behavior that occurs when invalid params are submitted
        Catgrade.any_instance.stub(:save).and_return(false)
        post :create, {:catgrade => { "libcatgrade" => "invalid value" }}, valid_session
        assigns(:catgrade).should be_a_new(Catgrade)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Catgrade.any_instance.stub(:save).and_return(false)
        post :create, {:catgrade => { "libcatgrade" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested catgrade" do
        catgrade = Catgrade.create! valid_attributes
        # Assuming there are no other catgrades in the database, this
        # specifies that the Catgrade created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Catgrade.any_instance.should_receive(:update).with({ "libcatgrade" => "MyString" })
        put :update, {:id => catgrade.to_param, :catgrade => { "libcatgrade" => "MyString" }}, valid_session
      end

      it "assigns the requested catgrade as @catgrade" do
        catgrade = Catgrade.create! valid_attributes
        put :update, {:id => catgrade.to_param, :catgrade => valid_attributes}, valid_session
        assigns(:catgrade).should eq(catgrade)
      end

      it "redirects to the catgrade" do
        catgrade = Catgrade.create! valid_attributes
        put :update, {:id => catgrade.to_param, :catgrade => valid_attributes}, valid_session
        response.should redirect_to(catgrade)
      end
    end

    describe "with invalid params" do
      it "assigns the catgrade as @catgrade" do
        catgrade = Catgrade.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Catgrade.any_instance.stub(:save).and_return(false)
        put :update, {:id => catgrade.to_param, :catgrade => { "libcatgrade" => "invalid value" }}, valid_session
        assigns(:catgrade).should eq(catgrade)
      end

      it "re-renders the 'edit' template" do
        catgrade = Catgrade.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Catgrade.any_instance.stub(:save).and_return(false)
        put :update, {:id => catgrade.to_param, :catgrade => { "libcatgrade" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested catgrade" do
      catgrade = Catgrade.create! valid_attributes
      expect {
        delete :destroy, {:id => catgrade.to_param}, valid_session
      }.to change(Catgrade, :count).by(-1)
    end

    it "redirects to the catgrades list" do
      catgrade = Catgrade.create! valid_attributes
      delete :destroy, {:id => catgrade.to_param}, valid_session
      response.should redirect_to(catgrades_url)
    end
  end

end
