require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe JointsController do

  # This should return the minimal set of attributes required to create a valid
  # Joint. As you add validations to Joint, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "per_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # JointsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all joints as @joints" do
      joint = Joint.create! valid_attributes
      get :index, {}, valid_session
      assigns(:joints).should eq([joint])
    end
  end

  describe "GET show" do
    it "assigns the requested joint as @joint" do
      joint = Joint.create! valid_attributes
      get :show, {:id => joint.to_param}, valid_session
      assigns(:joint).should eq(joint)
    end
  end

  describe "GET new" do
    it "assigns a new joint as @joint" do
      get :new, {}, valid_session
      assigns(:joint).should be_a_new(Joint)
    end
  end

  describe "GET edit" do
    it "assigns the requested joint as @joint" do
      joint = Joint.create! valid_attributes
      get :edit, {:id => joint.to_param}, valid_session
      assigns(:joint).should eq(joint)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Joint" do
        expect {
          post :create, {:joint => valid_attributes}, valid_session
        }.to change(Joint, :count).by(1)
      end

      it "assigns a newly created joint as @joint" do
        post :create, {:joint => valid_attributes}, valid_session
        assigns(:joint).should be_a(Joint)
        assigns(:joint).should be_persisted
      end

      it "redirects to the created joint" do
        post :create, {:joint => valid_attributes}, valid_session
        response.should redirect_to(Joint.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved joint as @joint" do
        # Trigger the behavior that occurs when invalid params are submitted
        Joint.any_instance.stub(:save).and_return(false)
        post :create, {:joint => { "per_id" => "invalid value" }}, valid_session
        assigns(:joint).should be_a_new(Joint)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Joint.any_instance.stub(:save).and_return(false)
        post :create, {:joint => { "per_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested joint" do
        joint = Joint.create! valid_attributes
        # Assuming there are no other joints in the database, this
        # specifies that the Joint created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Joint.any_instance.should_receive(:update).with({ "per_id" => "1" })
        put :update, {:id => joint.to_param, :joint => { "per_id" => "1" }}, valid_session
      end

      it "assigns the requested joint as @joint" do
        joint = Joint.create! valid_attributes
        put :update, {:id => joint.to_param, :joint => valid_attributes}, valid_session
        assigns(:joint).should eq(joint)
      end

      it "redirects to the joint" do
        joint = Joint.create! valid_attributes
        put :update, {:id => joint.to_param, :joint => valid_attributes}, valid_session
        response.should redirect_to(joint)
      end
    end

    describe "with invalid params" do
      it "assigns the joint as @joint" do
        joint = Joint.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Joint.any_instance.stub(:save).and_return(false)
        put :update, {:id => joint.to_param, :joint => { "per_id" => "invalid value" }}, valid_session
        assigns(:joint).should eq(joint)
      end

      it "re-renders the 'edit' template" do
        joint = Joint.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Joint.any_instance.stub(:save).and_return(false)
        put :update, {:id => joint.to_param, :joint => { "per_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested joint" do
      joint = Joint.create! valid_attributes
      expect {
        delete :destroy, {:id => joint.to_param}, valid_session
      }.to change(Joint, :count).by(-1)
    end

    it "redirects to the joints list" do
      joint = Joint.create! valid_attributes
      delete :destroy, {:id => joint.to_param}, valid_session
      response.should redirect_to(joints_url)
    end
  end

end
